### ISSUE TITLE
missing a file 'mme_hallucination.jsonl'

### ISSUE THREAD

**Issue by darkpromise98** [sangminwoo/RITUAL#1]
I have been reading your papers recently and I think they are very inspiring.

However, when I am running the evaluation codes for MME benchmark, I found the 'mme_hallucination.jsonl' is missing. Can you upload this file? Thanks a lot!

**Comment by jhyukjang** [comment]
We uploaded the file in [experiments/data/MME_Benchmark_release_version/mme_hallucination.jsonl](https://github.com/sangminwoo/RITUAL/blob/master/experiments/data/MME_Benchmark_release_version/mme_hallucination.jsonl).
Thank you for your understanding.
